exclude: # exclude matching issues
  - message: Examples and data necessary for running auto-tests
    paths:
      - docs/*.html
      - docs/examples/*
  - message: Trufflehog rules file contains regexes which might trigger the scanner
    paths:
      - trufflehog3/static/rules.yml
  - message: Integrity hash for highlight.min.js
    # NOTE pattern is re.Pattern, thus escaping of special characters might be required
    pattern: sha256-Uv3H6lx7dJmRfRvH8TH6kJD1TSK1aFcwgx\+mdg3epi8=
    paths:
      - docs/templates/*.mako
  - message: Not juicy directories
    paths:
      - translations
      - trans
      - assets/images
      - assets/image
      - assets/img
      - FUNDING.yml
      - FUNDINGS.yml
      - FUNDING.yaml
      - FUNDINGS.yaml
      - assets/fonts
      - assets/font
      - lang
      - language
      - languages
      - favicons
      - icons
      - font
      - fonts
      - style
      - theme
      - themes
      - .cache
      - jqgrid
      - .yarn
      - wp-content/plugins
      - l10n
      - venv
      - .venv
      - site-packages
      - dist-packages
      - wp-include
      - phpmyadmin
      - native/ios
      - locales
      - integreat-test-cms
      - integreat
      - native/android
      - bootstrap
      - fontawesome
      - font-awesome
      - vendor
      - vendors
      - stylesheets
      - xcschemes
      - assets/*.png
      - assets/*.jpg
      - assets/*.jepg
      - assets/*.gif
      - assets/*.icon
      - assets/*.ttf
      - assets/*.woff
      - assets/*.woff2
      - assets/*.webp
      - public/*.svg
      - public/*.png
      - public/*.jpg
      - public/*.gif
      - public/*.svgz
      - public/*.woff
      - public/*.woff2
      - public/*.ttf
      - assets/*.ico
      - assets/*.svg
      - assets/*.svgz
  - message: Not juicy file names
    paths:
      - deep_search.ghcbot
      - deep_file.list
      - poetry.lock
      - package-lock.json
      - flake.lock
      - webpack.config.babel.js
      - desktop.ini
      - README
      - README.md
      - web3.min.js
      - README.rst
      - LICENSE.txt
      - LICENSE
      - go.sum
      - yarn.lock
      - package.json
      - CODEOWNERS
      - CONTRIBUTORS
      - .prettierignore
      - yarn.json
      - project.pbxproj
      - .editorconfig
      - robot.txt
      - .Cargo.lock
      - Cargo.lock
      - Gemfile.lock
# - message: Not juicy file extensions
# paths:
# - \*\.css
# - \*\.less
# - \*\.scss
# - \*\.map
# - \*\.rst
# - \*\.lock
  - message: False positive matchs md5sum
    pattern: (?i)md5sum-.+
  - message: False positive matchs md5sum
    pattern: (?i)sha56-.+
  - message: False positive github commits
    pattern: '[a-f0-9]{16}'
  - message: False positive matchs hashes
    pattern: (?i)hash.+
  - message: Integrity hash for materialize.min.css
    # NOTE pattern is re.Pattern, thus escaping of special characters might be required
    pattern: sha256-kpeCd0c1zTgJMsU\+s8Pz4CwckI73qwpdYMTxTsRyO8A=
    paths:
      - docs/templates/*.mako
      - trufflehog3/static/report.html.j2
  - message: Integrity hash for materialize.min.js
    pattern: sha256-U/cHDMTIHCeMcvehBv1xQ052bPSbJtbuiw4QA9cTKz0=
    paths:
      - docs/templates/*.mako
      - trufflehog3/static/report.html.j2
  - message: Alphabet used in autotests
    pattern: abcdefghijklmnopqrstuvwxyz
    paths:
      - trufflehog3/helper.py
      - trufflehog3/models.py
      - trufflehog3/search.py
  - message: Commit hash used in autotests
    pattern: 9e404e6c59d286645b2465aacaf61108ebc12a3a
    paths:
      - trufflehog3/source.py
# NOTE you can also specify IDs or patterns together or without paths, e.g.
#
#   - message: Skip ID everywhere
#     id: high-entropy
#   - message: Skip ID on specific paths
#     id: high-entropy
#     paths:
#       - tests/data/*
#
#   - message: Skip pattern everywhere, case-insensitive
#     pattern: (?i)not-a-secret
#   - message: Skip pattern on specific paths, case-insensitive
#     pattern: (?i)not-a-secret
#     paths:
#       - tests/data/*

severity: low # minimum severity filter
ignore_nosecret: false # ignore inline 'nosecret' annotations
no_entropy: false # disable entropy checks
no_pattern: false # disable pattern checks

#branch: master # name of the repo branch to scan
depth: 250 # max commits depth for searching, only used if `no_history` is false
since: null # scan from the given commit hash, only used if `no_history` is false
no_current: false # disable current status check
no_history: false # disable commit history check

context: 1 # number of context lines to include
